title: "Max's blog"
description: >
  A site where I brain-dump and share stuff. Like all my RT but this time I am the author.
  Who knows, I might get on Hacker News one day
url: "https://max-mathieu.github.io"
twitter:
  username: maxence_mathieu
github:
  username: max-mathieu

# Build settings
markdown: kramdown
permalink: /:title/
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
