title: "Your blog title"
description: >
  Your blog description. This shows in meta fields for search engines and in your footer.
url: "https://your-username.github.io"
twitter:
  username: jekyllrb
github:
  username: jekyll
google_analytics: 

# Build settings
markdown: kramdown
permalink: /:title/
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-gist

exclude:
  - Gemfile
  - README.md
  - LICENSE
  - .gitignore
